package com.example.petapp.ui.addpet

interface AddPetOperations {
    fun onNameFieldValueChanged(name: String)
    fun onNameFieldCancelClicked()
    fun onDatePickerTextFieldValueChanged()
    fun onDatePickerTextFieldClicked()
    fun datePickerOnDismissRequest()
    fun datePickerOnConfirmedButtonClicked()
    fun datePickerOnDismissedButtonClicked()
    fun speciesMenuOnExpandedChanged(value: Boolean)
    fun speciesMenuOnDropdownMenuItemClicked(item: String)
    fun speciesMenuOnDismissRequest()
    fun breedMenuOnExpandedChanged(value: Boolean)
    fun breedMenuOnDropdownMenuItemClicked(item: String)
    fun breedMenuOnDismissRequest()
    fun onCancelButtonClicked()
    fun onNavigateButtonClicked(stage: AddPetScreenStage)
    fun onDoneButtonClicked()
    fun onWeightFieldValueChanged(value: String)
    fun onWeightFieldCancelClicked()
    fun onWeightFieldFocusCleared()
    fun onHeightFieldValueChanged(value: String)
    fun onHeightFieldCancelClicked()
    fun onHeightFieldFocusCleared()
    fun onLengthFieldValueChanged(value: String)
    fun onLengthFieldCancelClicked()
    fun onLengthFieldFocusCleared()
    fun onCircuitFieldValueChanged(value: String)
    fun onCircuitFieldCancelClicked()
    fun onCircuitFieldFocusCleared()
    fun onDescriptionTextFieldValueChanged(description: String)

}