package com.example.petapp.ui.navigation

enum class PetAppDestination {
    PET_MANAGER_ROUTE,
    SETTINGS_ROUTE,
    DASHBOARD_ROUTE,
    PET_DETAILS_ROUTE,
    PET_DETAILS_UPDATE_PET,
    PET_DETAILS_ADD_WEIGHT,
    PET_DETAILS_ADD_DIMENSIONS,
    PET_DETAILS_WEIGHT_DASHBOARD,
    PET_DETAILS_DIMENSIONS_DASHBOARD,
    PET_DETAILS_MEALS_DASHBOARD,
    PET_DETAILS_ADD_MEAL,
    PET_DETAILS_UPDATE_WEIGHT,
    PET_DETAILS_UPDATE_HEIGHT,
    PET_DETAILS_UPDATE_LENGTH,
    PET_DETAILS_UPDATE_CIRCUIT,
}